[profile.default]
src = "src"
out = "out"
libs = ["lib"]
via_ir = true
solc_version = "0.8.30"
auto_detect_remappings = false

[rpc_endpoints]
base-sepolia = "https://sepolia.base.org"
base = "https://mainnet.base.org"
